### ISSUE TITLE
Server Stuck in boot loop

### ISSUE THREAD

**Issue by DrMeepso** [Exiled-Team/EXILED#1104]
**Describe the bug**
Server keeps telling me a new version of exiled needs to be installed, installs it, then restart and it keeps downloading the same update

**To Reproduce**
Update to the new newest exiled 

**Expected behavior**
Server boots

**Server logs**
[Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured](https://pastebin.com/Xt7Drkhp)

**EXILED Version ("latest" is not a version):**

**Results of `show plugins` command in console:**
Cant run commands

**Additional context**

**Comment by joker-119** [comment]
[2022-02-20 12:12:32.379 +13:00] Exiled.Loader - Version 5.0.0-beta.2
[2022-02-20 12:12:39.559 +13:00] [INFO] [Exiled.Updater] Found the smallest version of Exiled - Exiled.API:5.0.0-beta.1


Either you have an Exiled.API.dll in the plugins folder, or you have two of them in the dependencies folder, or for some reason the installer is unable to replace the one that exists (permission issue).

Try shutting down the server and using the normal installer, or download the latest release and manually replace your API.dll file in EXILED/Plugins/dependencies
Also make sure there's no duplicate Exiled.x.dll files anywhere.
