### ISSUE TITLE
Suggestion for improvement.

### ISSUE THREAD

**Issue by Tamago4a** [Exiled-Team/EXILED#1151]
Perhaps I will write something that is impossible to implement. But I run into the problem of RAM leak quite often. To do this, you have to remove half of the plugins and look for the cause. But it also happens that 2 plugins can fail at once. Or the leak may occur infrequently, for example, once every couple of days. Then the search for a problem stretches for a month.

Is it possible to do something about this at the EXILED code level? Perhaps my suggestion is not feasible, but it would be cool if after each action, even the smallest one, there was some information about the used RAM in the console.

**Comment by joker-119** [comment]
A memory profiler isn't something that falls into what EXILED itself should be doing. You can make a plugin for it but all it can do is tell you x memory is being used, not where it's being used or what objects.

There's at least 2 basegame memory leaks we are aware of, none have been attributed to EXILED, but you need to attach a debugger to the server process that logs what object types are using how much memory etc.

**Comment by Tamago4a** [comment]
It's a pity. Do I understand correctly that without the intervention of the game developers, I will not be able to build this debugger into the server?

**Comment by Tamago4a** [comment]
Are you talking about this?
https://github.com/dnSpy/dnSpy-Unity-mono
https://github.com/0xd4d/dnSpy

**Comment by joker-119** [comment]
Neither of those are anywhere close to what you need.
You can use dotnet to create a memory dump of the process, go learn how to google.
