### ISSUE TITLE
Autonuke goes off after nuke has been detonated

### ISSUE THREAD

**Issue by Oyplap** [Exiled-Team/EXILED#1288]
**Describe the bug**
When the nuke goes off after manually detonating / activating it, the autonuke gets activated which shouldn't happen.

**To Reproduce**
1. Enable nuke.
2. Go to surface and activate the nuke.
3. After detonation, wait for the autonuke.
4. Autonuke goes off.

**Expected behavior**
Autonuke shouldn't activate after a successful detonation (which a player has activated).

**EXILED Version ("latest" is not a version):**
v5.2.1

**Comment by zhaguanyang** [comment]
Which auto nuke, base game, or Common utils?

**Comment by Oyplap** [comment]
> Which auto nuke, base game, or Common utils?

Obviously Common Utils ;)

**Comment by zhaguanyang** [comment]
> > Which auto nuke, base game, or Common utils?
> 
> Obviously Common Utils ;)

Then why are you reporting the issue on EXILED repo lol

**Comment by Oyplap** [comment]
Oh shit, I have a monkey brain. I probably clicked on the wrong repo. Sorry about that
