### ISSUE TITLE
[BUG] 173 using tantrum crashes server

### ISSUE THREAD

**Issue by ScuutScuutLucas** [Exiled-Team/EXILED#1312]
**Describe the bug**
Whenever 173 does tantrum it crashes the server and kicks everyone. 

**To Reproduce**
1. Spawn yourself as 173
2. Use the tantrum thing as 173
3. Server crashes, kicks everyone and restarts itself

**Expected behavior**
173 can poop without the server crashing

**Server logs**
https://pastebin.com/T37NJS4q

**EXILED Version (5.3.0-beta.2):**

**Additional context**

**Comment by ScuutScuutLucas** [comment]
Finally got a better error log that actually says something

[message (7).txt](https://github.com/Exiled-Team/EXILED/files/9045904/message.7.txt)

**Comment by moseechev** [comment]
YEAH MAN SAME HERE
I actually had to forbid 173 from placing tantrum because otherwise it makes it impossible to play

**Comment by louis1706** [comment]
Please can you say to me if your server run on linux ?

**Comment by louis1706** [comment]
https://discord.com/channels/656673194693885975/994657514564108340/994657552589664378 if people want to discuss it on discord

**Comment by SpaceBuddy231** [comment]
> YEAH MAN SAME HERE I actually had to blacklist 173 because otherwise it makes it impossible to play

How to blacklist SCP-173?

**Comment by SpaceBuddy231** [comment]
> **Describe the bug** Whenever 173 does tantrum it crashes the server and kicks everyone.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Spawn yourself as 173
> 2. Use the tantrum thing as 173
> 3. Server crashes, kicks everyone and restarts itself
> 4. See error
> 
> **Expected behavior** 173 can poop without the server crashing
> 
> **Server logs** https://pastebin.com/T37NJS4q
> 
> **EXILED Version (5.3.0-beta.2):**
> 
> **Additional context** Add any other context about the problem here.

Same

**Comment by SpaceBuddy231** [comment]
Same
