### ISSUE TITLE
Installer issue - "No usable version of libssl was found"

### ISSUE THREAD

**Issue by Wrasek** [Exiled-Team/EXILED#1382]
What's wrong here ? I'm installing Exiled from installer, I have got newest libssl.
I use latest installer
scp@wrasekinc:~/serwer$ ./Exiled.Installer-Linux
Exiled.Installer-Linux-3.2.1.0
AppData folder: /home/scp/.config
Receiving releases...
Prereleases included - False
Target release version - (null)
No usable version of libssl was found
Aborted (core dumped)

**Comment by Artin-13** [comment]
@Wrasek how did you solve this?
