### ISSUE TITLE
[BUG] Custom Grenades Not Working For Any Plugins

### ISSUE THREAD

**Issue by Redforce04** [Exiled-Team/EXILED#1403]
**Describe the bug**
Custom grenades are broken.
Whenever a custom grenade is thrown, it will wait the normal fuse time and then promptly disappear without any trace, logs, or any expected responses. Furthermore, the player that threw the grenade is not able to open their inventory with tab, unless they have an item they can switch to (ex. they have a gun so they switch to the gun without pressing tab). Upon viewing the inventory, the custom grenade is still in their inventory. Other players in the server can only see when the grenade is equipped, but not when it is thrown. The only default Custom Item that works is the C4-119.

**To Reproduce**
1. Load the server with the Custom Items plugin or any plugin with custom grenades.
2. Spawn in as any human class.
3. Spawn a custom grenade and throw the grenade. (EM-119, IG-119, any other custom grenades except C4-119)
3. No errors are logged, and you will be unable to open your inventory unless you can switch into a weapon. Additionally, your inventory will still contain the custom grenade.

**Expected behavior**
The grenade should explode and/or execute the custom grenade actions. The player should be able to view their inventory. Other players should be able to see the grenade be thrown, and perform the custom actions.

**Server logs**
Local Admin Log - [https://pastebin.com/UBJ8txaE](https://pastebin.com/UBJ8txaE)

**EXILED Version:**
5.3.0

**SCP-SL Version:**
11.2.1

**Results of `show plugins` command in console:**
Plugins - [https://pastebin.com/zDGC7aCU](https://pastebin.com/zDGC7aCU)

**Additional context**
May be partly due to a sync issue because only the player throwing the object sees the grenade being thrown. Other people watching, only see the grenade being held. Other people can see the grenade being dropped, and can pick it up.

**Media:**
1st Person View:
https://user-images.githubusercontent.com/74625280/188331874-91f104ba-4adf-4e50-aba6-606ed898d9e4.mp4

3rd Person View:
https://user-images.githubusercontent.com/74625280/188332051-5344145a-4dee-4ee0-8848-160c35f41d80.mp4

**Comment by BuildBoy12** [comment]
Fixed by #1384

**Comment by IRacle1** [comment]
Oh, that was merged to dev after 5.3.0 release💀

**Comment by IRacle1** [comment]
so it isn't fixed

**Comment by IRacle1** [comment]
@NaoUnderscore ^

**Comment by louis1706** [comment]
Always not fixed
