### ISSUE TITLE
[BUG] Artificial Health bar does not update for SCPs when the processes are modified 

### ISSUE THREAD

**Issue by manninxn** [Exiled-Team/EXILED#1453]
**Describe the bug**
When you modify a process' limit and amount on an scp, the maximum value of the bar does not update

**To Reproduce**
1. Add an event handler for Spawned
2. If the player is an SCP, set the limit and current amount of each process to a value smaller than the default, like 200
3. The artificial health bar will appear as if it is almost empty, despite being at its maximum value

**Expected behavior**
The artificial health bar to update properly 

**Server logs**
no errors

**EXILED Version ("latest" is not a version):**
5.3.2

**Results of `show plugins` command in console:**
`[2022-12-19 15:05:22.456 -05:00] Total number of plugins: 11
                                 Enabled plugins: 11
                                 Disabled plugins: 0

                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 5.3.2.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 ReportToDiscord:
                                        - Author:
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: report_to_discord
                                        - Priority: Medium
                                 NoGhostingForZombies:
                                        - Author:
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: no_ghosting_for_zombies
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 5.3.2.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 5.1.0.0
                                        - Required Exiled Version: 5.1.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 5.3.2.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 5.3.2.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 5.3.2.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 TeslaGate:
                                        - Author:
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: tesla_gate
                                        - Priority: Medium
                                 SCPImprovement:
                                        - Author:
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.3.2.0
                                        - Prefix: s_c_p_improvement
                                        - Priority: Medium`

**Comment by louis1706** [comment]
Thanks for the report i will continue to try to found a fix for it

**Comment by louis1706** [comment]
it's seems than now it's working (didn't find the reason but since it's fix i close it)
