### ISSUE TITLE
[BUG] Role.Set() spawns player in, however still renders player model

### ISSUE THREAD

**Issue by PundaVR** [Exiled-Team/EXILED#1504]
## 6.0.0-beta.21

**Describe the bug**
Code: .Role.Set(newRole, reason) 
The code will work, and I will be set as the correct role. However, I still see the character model of the SCP. I haven't tested with player classes, only with SCPs, but I assume the same would happen.
This didn't just happen to me, happened to other people who I was testing the plugin with

**To Reproduce**
1. use Role.Set() in code
2. Spawn via command or however you setup to execute your code
3. See the problem

**Expected behavior**
No Character Model

**Server logs**
none

**EXILED Version ("latest" is not a version):**
6.0.0-beta.21

**Results of `show plugins` command in console:**
 Total number of plugins: 9
                                 Enabled plugins: 9
                                 Disabled plugins: 0
                                 
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 RespawnTimer:
                                        - Author: Michal78900
                                        - Version: 4.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: respawn_timer
                                        - Priority: Medium
                                 Punda's Pantheon Plugin:
                                        - Author: Punda
                                        - Version: 2.0.6
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: pundas_pantheon_plugin
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 MapEditorReborn:
                                        - Author: Michal78900
                                        - Version: 2.2.0
                                        - Required Exiled Version: 5.3.0
                                        - Prefix: map_editor_reborn
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium

**Additional context**
SCP-173: https://www.youtube.com/watch?v=F4WBIC8x3Tw
SCP-049: https://www.youtube.com/watch?v=PwG-XvHq76E

**Comment by PundaVR** [comment]
still occuring in beta.24

**Comment by xNexus-ACS** [comment]
I saw the videos, the error happened here is a basegame bug that has been already reported

**Comment by warden161** [comment]
close this?
