### ISSUE TITLE
[BUG] Dogs Captured Voices isnt playing the voices

### ISSUE THREAD

**Issue by TheEeveeModerator** [Exiled-Team/EXILED#1584]
**Describe the bug**
Dogs voice isnt working
**To Reproduce**

**Expected behavior**
When dog kills a player it should play their voice
**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured
(do not have due to me being staff not owner)
**EXILED Version ("latest" is not a version):**
6.0 BETA .25

**Results of `show plugins` command in console:**
n/a

**Additional context**
No

**Comment by TheEeveeModerator** [comment]
the owner of the server im staff on first reported this bug last night when he wwas informed by a fellow staff that it wasnt working

**Comment by Misaka-ZeroTwo** [comment]
Should be fixed in the next release

**Comment by louis1706** [comment]
Fixed
