### ISSUE TITLE
[ENHANCEMENT] Player.DisplayNickname defaults to Player.Nickname when null

### ISSUE THREAD

**Issue by tpd1864blake** [Exiled-Team/EXILED#1585]
It is possible for Player.DisplayNickname to be null if they do not have an assigned nickname. The Display Name is what appears on the player list and should be the name accessed by plugins when displaying names. It would be easier if plugins could just do Player.DisplayNickname without having to run extra checks.

EXILED.API.Features.Player.cs - Line 301-305
Current code:
```
public string DisplayNickname
{
    get => ReferenceHub.nicknameSync.Network_displayName;
    set => ReferenceHub.nicknameSync.Network_displayName = value;
}
```
Proposed code:
```
public string DisplayNickname
{
    get => ReferenceHub.nicknameSync.Network_displayName ?? Nickname;
    set => ReferenceHub.nicknameSync.Network_displayName = value;
}
```
The proposed code will return the player's Display Name if it is not null, otherwise it will return their Name

**Comment by Misaka-ZeroTwo** [comment]
#1586

**Comment by louis1706** [comment]
@tpd1864blake now use CustomName if you don't want <color=DJdz>*</color>
