### ISSUE TITLE
[BUG] SCPs crash sometimes when setting player scale

### ISSUE THREAD

**Issue by tpd1864blake** [Exiled-Team/EXILED#1589]
**Describe the bug**
In a semi-rare subset of cases, setting the Player.Scale property of any player will cause every SCP in the round to be disconnected from the server.

**To Reproduce**
Set the scale of a player, for example, to `Player.Scale = new(1.5f, 1.5f, 1.5f);` with 1 (or more) people as an SCP

**Expected behavior**
SCPs should not be disconnected when a player's Scale property is modified.

**Server logs**
old image but this is the error that appears when they get disconnected
![image](https://user-images.githubusercontent.com/70983641/216220770-07de4f9c-45c6-47c0-b894-7f87be49c5e1.png)

**EXILED Version ("latest" is not a version):** 6.0.0-beta.25

**Results of `show plugins` command in console:**

**Additional context**
In my plugin called `skull_island`, I have random effects from taking painkillers and one of those effects is resizing the player. Sometimes when the player gets resized, every SCP in the round immediately gets disconnected.

**Comment by Misaka-ZeroTwo** [comment]
Sounds like a skill issue, there are a couple of my plugin characters modify the player size. But I have never heard scps got disconnected randomly.

**Comment by louis1706** [comment]
I assume try to get help on discord but this seems to not being caused by exiled
