### ISSUE TITLE
[BUG] 096 Tutorial Trigger

### ISSUE THREAD

**Issue by BenFRC5147** [Exiled-Team/EXILED#1596]
**Describe the bug**
When we have the   can_tutorial_trigger_scp096: false config set, Tutorial still triggers 096

Whenever there is an 096 in the round, we get an error 
The preciously mentioned error log did not have to do with exiled events, I just couldn't read the big sign saying *SCPStats* however, the 096 trigger is still occurring for tutorials.

**To Reproduce**
Enable the config, have an 096 in the round, see the error, set yourself to tutorial and look at 096, see he gets triggered.

**Expected behavior**
No error is logged, and Tutorial doesn't trigger 096

**Server logs**
Do not have detailed server logs, not a server owner, just an Admin, server owner isn't available right now to get log, will supply when I have it if issue isn't found out before then.

**EXILED Version ("latest" is not a version):**
Exiled 6 beta 25

**Results of `show plugins` command in console:**

![image](https://user-images.githubusercontent.com/13715542/216851086-cbda70e3-80cf-4361-968d-55d1f38541e2.png)
![image](https://user-images.githubusercontent.com/13715542/216851092-880d3982-67b8-4dd6-bfda-c190622110ca.png)
![image](https://user-images.githubusercontent.com/13715542/216851103-ede355be-2ab9-4afa-8504-935ea70e10c4.png)
![image](https://user-images.githubusercontent.com/13715542/216851122-1796b41a-c30d-400e-9005-83e45a460ef4.png)

**Additional context**

**Comment by louis1706** [comment]
https://github.com/Exiled-Team/EXILED/pull/1633

Bug fixed
