### ISSUE TITLE
[BUG] 914 upgrades all inventory

### ISSUE THREAD

**Issue by LaFesta1749** [Exiled-Team/EXILED#1600]
**Describe the bug**
914 upgrades all of the player inventory, not just the held item. I've searched all of the configs relating to 914 or not and could not find the issue.

**To Reproduce**
1. Go to 914 and have an inventory of items (or at least two),
2. Upgrade while in the chamber,
3. Have your whole inventory upgraded instead of the held item.

**Expected behavior**
Expected to upgrade only the **held** item.

**Server logs**
https://pastebin.com/n3F88GvL

**EXILED Version ("latest" is not a version):**
"[Broken Exiled hotfix Part 3 + LOTS OF API](https://github.com/Exiled-Team/EXILED/releases/tag/6.0.0-beta.25)"

**Results of `show plugins` command in console:**
                   [06-02-2023 23:15] >>> show plugins
                   [06-02-2023 23:15] Total number of plugins: 3
                   Enabled plugins: 3
                   Disabled plugins: 0

                   Exiled.Events:
                        - Author: Exiled Team
                        - Version: 6.0.0.0
                        - Required Exiled Version: 6.0.0.0
                        - Prefix: exiled_events
                        - Priority: Highest
                   Exiled.Updater:
                        - Author: Exiled.Updater
                        - Version: 3.1.1.0
                        - Required Exiled Version: 6.0.0.0
                        - Prefix: exiled_updater
                        - Priority: Medium
                   Exiled.Permissions:
                        - Author: Exiled Team
                        - Version: 6.0.0.0
                        - Required Exiled Version: 6.0.0.0
                        - Prefix: exiled_permissions
                        - Priority: Medium

**Additional context**
Is there a fix to this? It's breaking the whole server at this point.
Server IP if needed for tests: **_213.16.57.9:7777_**

**Comment by Misaka-ZeroTwo** [comment]
Fixed in next exiled release.

**Comment by LaFesta1749** [comment]
Is there any ETA on it perhaps?

**Comment by Misaka-ZeroTwo** [comment]
You can get EXILED BETA role and it's in the testing release.

**Comment by Misaka-ZeroTwo** [comment]
Probably one or two days?

**Comment by louis1706** [comment]
it's now fixed
