### ISSUE TITLE
Need Help Migrating Project to new Exiled Version

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [Exiled-Team/EXILED#1652]
So I've Installed a new version of Exiled, and a number of things have broken. IConfig in Config.cs wants a IConfig.debug implimentation. The custom Remote Admin Command cs files can't find CommandHandler, ICommand, and ICommandSender as types or name spaces. I fixed the rest of the files but I still need help. The References I have are 0Harmony, Assembly-CSharp, Exiled.Api, Exiled.CreditTags, Exiled.CustomItems, Exiled.CustomRoles, Exiled.Events, Exiled.Loader, Exiled.Permissions, Exiled.Updater, SemanticVersioning, SemVer, System, and YamIDotNet. Plz Help.

**Comment by louis1706** [comment]
Come one Discord in https://discord.com/channels/656673194693885975/1002713309876854924

**Comment by theOneTrueFunniBoi** [comment]
I'm not on the discord.
