### ISSUE TITLE
[BUG] InteractingDoorEventArgs ev.IsAllowed not working

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1733]
**Describe the bug**
If door is locked player can't open it, even if  in InteractingDoorEventArgs property ev.IsAllowed set  to true

Reported by @ITeMbI4 in https://discord.com/channels/656673194693885975/1079489116875522098/1079489116875522098

**Comment by ITeMbI4** [comment]
Maybe it was fixed it that pr?
https://github.com/Exiled-Team/EXILED/pull/1644

But I see you closed it @Misaka-ZeroTwo

**Comment by Misaka-ZeroTwo** [comment]
> Maybe it was fixed it that pr? #1644
> 
> But I see you closed it @Misaka-ZeroTwo

It was both for bug fixing and making ``IsAllowed`` doing what it's supposed to be doing. However, it's a breaking change so I closed it.

**Comment by louis1706** [comment]
> > Maybe it was fixed it that pr? #1644
> > 
> > But I see you closed it @Misaka-ZeroTwo
> 
> It was both for bug fixing and making ``IsAllowed`` doing what it's supposed to be doing. However, it's a breaking change so I closed it.

Reopen it. We are just going to wait Exiled 7

**Comment by Misaka-ZeroTwo** [comment]
> > > Maybe it was fixed it that pr? #1644
> > > But I see you closed it @Misaka-ZeroTwo
> > 
> > 
> > It was both for bug fixing and making `IsAllowed` doing what it's supposed to be doing. However, it's a breaking change so I closed it.
> 
> Reopen it. We are just going to wait Exiled 7

Done

**Comment by ITeMbI4** [comment]
Need testing, but I think it's fixed with 13.0 update
![image](https://github.com/Exiled-Team/EXILED/assets/46756889/976844f3-b070-4173-961f-314253d3aa4c)
@Misaka-ZeroTwo
