### ISSUE TITLE
[BUG] Leaved players don't destroyed

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1738]
Sometimes players can be null, it happens randomly
![image](https://user-images.githubusercontent.com/46756889/233420494-549c1719-79f4-47e8-bee5-8bf657d5016b.png)

Reported by @ITeMbI4 in https://discord.com/channels/656673194693885975/1076519768800112671

**Comment by joker-119** [comment]
Cannot reproduce, need server logs for more information.

**Comment by ITeMbI4** [comment]
Idk, it happens randomly
Need some time to determine exact reproduce actions

**Comment by louis1706** [comment]
> Idk, it happens randomly
> Need some time to determine exact reproduce actions

It's certainly a plugin who causing it. And not exiled directly (could be indirectly)
