### ISSUE TITLE
[BUG] Player.CustomInfo setter throws error when custom info value is valid

### ISSUE THREAD

**Issue by joker-119** [Exiled-Team/EXILED#1741]
**Describe the bug**
The error thrown by the Player.CustomInfo setter regex will appear in the server console sometimes even when the custom info string being set is not invalid.

**To Reproduce**
1. Set a player's custom info with the `[` or `<` symbol in the string.
IE: `playername <3`

**Expected behavior**
Nothing, as this is a perfectly valid custom info and displays on the client without issues.

**Server logs**
N/A

**EXILED Version ("latest" is not a version):**
6.1.0-rc.1

**Results of `show plugins` command in console:**
Only plugins are EXILED and a test plugin that sets their custom info to a string of my choosing via command.

**Comment by louis1706** [comment]
We need a NW dev to give us the part of missing code than we have got with Beryl
