### ISSUE TITLE
[BUG] Shot event doesn't fire

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1745]
**Describe the bug**
Shot event doesn't fire if you don't hit a player

**Expected behavior**
Event should fire.

Reported by @TtroubleTT

**Comment by Misaka-ZeroTwo** [comment]
reproduced

**Comment by joker-119** [comment]
Was this only a bug in buckshot guns only, or is this still a thing in other guns?

**Comment by Misaka-ZeroTwo** [comment]
> Was this only a bug in buckshot guns only, or is this still a thing in other guns?

Originally for all guns. But since my fix is merged, now it's only buckshot only
