### ISSUE TITLE
[BUG] PreAuthenticating event does not fire when connecting to a server with whitelist enabled

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1749]
**Describe the bug**
Per title

Reported by: @Ficus-x

**Comment by joker-119** [comment]
While this is P1, the only way to fix it would be by re-adding a preauth patch for this event. Idk why it was removed in the first place but there's a lot that could go wrong with doing so, thus this P1 will not be considered blocking.

**Comment by Misaka-ZeroTwo** [comment]
Re-open due to the fix being broken.

**Comment by louis1706** [comment]
I will look at this after the next Release of NW since they will entirely rewrite this method

**Comment by ALEXWARELLC** [comment]
@Misaka-ZeroTwo Hey!

After doing some testing, it seems `PreAuthenticating` is working with Whitelist enabled, so feel free to close this issue if you wish.

Thanks :)
