### ISSUE TITLE
[BUG] DamageType.Unknown when SCP kill a player with a Firearm

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1750]
Reported by: @louis1706

**Comment by xNexus-ACS** [comment]
basegame

**Comment by louis1706** [comment]
> basegame

That can't be Basegame lol since it's Firearm damage and DamageType is given by exiled xD

**Comment by louis1706** [comment]
#1715 will fix it

**Comment by xNexus-ACS** [comment]
> > basegame
> 
> That can't be Basegame lol since it's Firearm damage and DamageType is given by exiled xD

a SCP can't use Firearms, since its uses the same attack key, that's why its unknown, I don't see why we need to correct something that is basegame

**Comment by louis1706** [comment]
> > > basegame
> > 
> > 
> > That can't be Basegame lol since it's Firearm damage and DamageType is given by exiled xD
> 
> a SCP can't use Firearms, since its uses the same attack key, that's why its unknown, I don't see why we need to correct something that is basegame

that not BaseGame SCP can use Firearm just give to your self with RA and attack someone with this firearm
