### ISSUE TITLE
[Feature Request] Separated configs not working

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1762]
**Describe the bug**
When you use the command econfig separate to separate the configs, the changes are not kept after reboot and the loader.yml file is ignored.

Exiled version:  6.1.0-rc.1

How to reproduce it:
Open up an Exiled server
Run the command econfig separate
Delete the 7777-config.yml file, as instructed by the message
Restart the server

What should happen:
There should be no 7777-config.yml file generated and the server should take the configs for each plugin from their respective folder, as well as consider the configs separated.

What happens:
The 7777-config.yml file is generated with default options, the loader.yml file is ignored despite being created and the configs are reset to defaults. The server does not consider the configs to be separated, as noted by the fact that it gives an error when you try to merge the configs. 
Additional information:
I have tested this bug with localadmin and it exhibits the same behaviour. The reason why I use multiadmin is because it's easier to restart and to manage servers. 

Reported by: @AirDog46

**Comment by joker-119** [comment]
The command doesn't update the loader.yml's config file at all. It never has, and needs to be updated manually. This isn't so much a bug as it is a missing feature.
