### ISSUE TITLE
[BUG] Particle disruptor / Jailbird disappear when picked up

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1764]
When Particle disruptor and/or Jailbird spawned via plugin and player tries to pick it up, it just disappears without any errors
Using EXILED [6.1.0-rc.1](https://github.com/Exiled-Team/EXILED/tree/6.1.0-rc.1)

**Comment by Misaka-ZeroTwo** [comment]
Confirmed to be an issue with ``Pickup.Create``, ``Item.Create(itemType).CreatePickup()`` can be used temporarily as a workaround.

**Comment by louis1706** [comment]
it's certainly because Particle disruptor appears with no ammo
