### ISSUE TITLE
[BUG] ev.IsTransmitting is always true in Transmitting

### ISSUE THREAD

**Issue by Ficus-x** [Exiled-Team/EXILED#1766]
**Descibe the bug**
It does not matter, ev.IsTransmitting is always true

1. Insert logs in Transmissing event
2. Test and look at logs

**Expected behavior**
must be true or false depending on situation.

**EXILED Version ("latest" is not a version):**
6.1.0-rc.1

**Results of `show plugins` command in console:**
Does not matter

**Additional context**
None

**Comment by joker-119** [comment]
What event are you even referring to here?

**Comment by Misaka-ZeroTwo** [comment]
Transmitting event I believe

**Comment by Misaka-ZeroTwo** [comment]
It invokes whenever the player presses the transmission key(according to the docs) so I assume it should always be true?

**Comment by Misaka-ZeroTwo** [comment]
![image](https://github.com/Exiled-Team/EXILED/assets/45165615/90879233-6b04-42d7-9180-c69ec534cadf)
Currently, the event is inserted before NetworkServer.SendToReady, which is why it doesn't fire when player is not transmitting
