### ISSUE TITLE
[BUG] Events firing when player is not verified

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1802]
**Describe the bug**
As described by the title.
**EXILED Version ("latest" is not a version):**
7.0.0-rc.2

**Comment by joker-119** [comment]
Need more info on this. I'm using hurting event a lot and ev.Player works fine. Is this only happening when they disconnect?

**Comment by Misaka-ZeroTwo** [comment]
> Need more info on this. I'm using hurting event a lot and ev.Player works fine. Is this only happening when they disconnect?

Initially reported that Common-util having this problem. But likely caused by disconnect.

**Comment by louis1706** [comment]
i only get this issue with older version of Exiled happening a lot with Exiled 6 and never seen it with Exiled 7

**Comment by Misaka-ZeroTwo** [comment]
Reproduced by leaving the game before getting verified.

**Comment by Misaka-ZeroTwo** [comment]
https://pastebin.com/Z6FsbP7j
