### ISSUE TITLE
[BUG] Escape event

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1810]
How to reproduce: 
Be a class (in my instance a special scientist class) that on escape method isnt allowed to escape. If it goes into escape zone it gives all the tickets to their team. In my case mtf. 

Expected outcome: 
Does not give tickets if they cant actually escape. 

Video:  https://medal.tv/games/scp-secret-laboratory/clips/19BYbWhNbp1Vnv/d13373BlLEy9?invite=cr-MSwzRkssNjYyODkyMjgs

**Comment by ITeMbI4** [comment]
https://github.com/Exiled-Team/EXILED/pull/1807 this one?

**Comment by Misaka-ZeroTwo** [comment]
yup
