### ISSUE TITLE
[BUG] Item and Pickup extension doesn't contain new SCPs

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1812]
**Describe the bug**
As title - https://github.com/Exiled-Team/EXILED/blob/master/Exiled.API/Extensions/ItemExtensions.cs
![image](https://github.com/Exiled-Team/EXILED/assets/46756889/ad7edaf6-1f88-42ae-9950-675f82c7327b)

**EXILED Version ("latest" is not a version):**
[7.0.0-rc.3](https://github.com/Exiled-Team/EXILED/tree/7.0.0-rc.3)

**Comment by xNexus-ACS** [comment]
@ITeMbI4 you're watching the Master branch, check the dev one

**Comment by ITeMbI4** [comment]
Dev branch
https://github.com/Exiled-Team/EXILED/blob/640c10e692a39ae9243fc468ddf28b4690414319/Exiled.API/Extensions/ItemExtensions.cs#LL49C8-L49C8

Missing `SCP1576`
