### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Miramista091** [Exiled-Team/EXILED#1813]
When i start the servor i see this : [WARN] [Exiled.Permissions] Permissions file at C:\Users\blond\AppData\Roaming\EXILED\Configs\permissions.yml is missing, creating.

I dont understand what i need to do.

**Comment by VALERA771** [comment]
Not a bug. It means that it's created permission file in EXILED directiory. This is normal

**Comment by VALERA771** [comment]
Also if you have another issues before posting them here as a bug ask about them in [support channel](https://discord.com/channels/656673194693885975/656709515936530445)

**Comment by Misaka-ZeroTwo** [comment]
> Not a bug. It means that it's created permission file in EXILED directiory. This is normal

Closing, because ^
