### ISSUE TITLE
[BUG] Game round restart bug

### ISSUE THREAD

**Issue by ardi125** [Exiled-Team/EXILED#1843]
**Describe the bug**
when server restarts it crashes server when server is using 5950X 128 ddr4 dedicated server it pops up with force connection or forced kick i was told its a exiled bugg

**Comment by Misaka-ZeroTwo** [comment]
Can you provide LA logs from server-side? I use ``sr`` and ``rnr`` a lot, never had this issue.

**Comment by Misaka-ZeroTwo** [comment]
I am also pretty sure the game itself has problems with restarting…
