### ISSUE TITLE
[BUG] ev.Player in LeftEventArgs leads to JoinedEventArgs 

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1856]
**Describe the bug**
Reported by @NotIntense in https://discord.com/channels/656673194693885975/1116929890890035300
I can't tell if this is a bug, or just incorrect naming, however, the image describes it all
![image](https://github.com/Exiled-Team/EXILED/assets/46756889/78c8af5d-01be-4501-8675-b6f6d877ce40)

https://github.com/Exiled-Team/EXILED/blob/640c10e692a39ae9243fc468ddf28b4690414319/Exiled.Events/EventArgs/Player/LeftEventArgs.cs#L15

**EXILED Version ("latest" is not a version):**
7.0.0-rc.5

**Comment by ALEXWARELLC** [comment]
Why does LeftEventArgs inherit JoinedEventArgs?

**Comment by ALEXWARELLC** [comment]
As far as i can tell, this is not an issue as LeftEventArgs inherits from JoinedEventArgs. This is why it shows up as `Gets the Joined Player`. I don't see why this issue is still open.

**Comment by ALEXWARELLC** [comment]
This appears to be intentional as `LeftEventArgs` inherits from `JoinedEventArgs`.
