### ISSUE TITLE
[BUG] Jailbird break method doesn't work

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1858]
**Describe the bug**
No any errors, it just does nothing.
In master was this code and it works fine
```
        public void Break()
        {
            Base._broken = true;
            Base.SendRpc(JailbirdMessageType.Broken);
        }
```

**EXILED Version ("latest" is not a version):**
7.0.0-rc.5

**Comment by louis1706** [comment]
Fixed
