### ISSUE TITLE
[BUG] ev.MaximumRespawnAmount on RespawningTeamEvent

### ISSUE THREAD

**Issue by Marco15453** [Exiled-Team/EXILED#1880]
**Describe the bug**
When using the RespawningTeamEvent and setting ev.MaximumRespawnAmount to example 8 it returns as error
Non-negative number required.

**To Reproduce**
**It was only me on the server as spectator**
1. Make an plugin that uses ev.MaximumRespawnAmount on RespawningTeamEvent
   (Example: ev.MaximumRespawnAmount = 8)
2. Trigger an Respawn
3. See error

**Expected behavior**
It limits the players to the specified value without throwing an error

**Server logs**
https://pastebin.com/8kESi7ks

**EXILED Version ("latest" is not a version):**
7.0.0-rc.5

**Results of `show plugins` command in console:**
https://pastebin.com/1dBAy6MW

**Additional context**
-/-

**Comment by joker-119** [comment]
Fixed in [eb45e47](https://github.com/Exiled-Team/EXILED/commit/eb45e47cdfa95a8ee451d5e01144ed36c6eb4c22)
