### ISSUE TITLE
[BUG] Setting ev.ItemsToDrop in Dying event does nothing

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1882]
**Describe the bug**
There is no implementation on it.

**EXILED Version ("latest" is not a version):**
7.0.0-rc.5

**Comment by VALERA771** [comment]
I'm gonna test my fix on weekend cuz exiled on my laptop is little broken and I can't build there tear version

**Comment by louis1706** [comment]
any news ? @VALERA771

**Comment by VALERA771** [comment]
Last PR broke everything. So I can try again

**Comment by louis1706** [comment]
> Last PR broke everything. So I can try again

:trollface: good

**Comment by ALEXWARELLC** [comment]
> 

We do a little trolling.

**Comment by VALERA771** [comment]
Occurs in EXILED 8?

**Comment by Misaka-ZeroTwo** [comment]
> Occurs in EXILED 8?

I forgot which event was referred by this issue lol
