### ISSUE TITLE
[BUG] New pickups don't present in the Pickup.List

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1898]
**Describe the bug**
New pickups don't present in the `Pickup.List` and can't be detected/destroyed

**To Reproduce**
1. Create new pickup
2. Try to destroy it

**Expected behavior**
It destroys

**EXILED Version ("latest" is not a version):**
7.0.5

**Comment by IRacle1** [comment]
How did you spawn pickups? for me `Pickup::CreateAndSpawn` works fine

**Comment by ITeMbI4** [comment]
@IRacle1 spawn works fine, but you can't do anything with pickup further with `Pickup.Get()`

**Comment by IRacle1** [comment]
> @IRacle1 spawn works fine, but you can't do anything with pickup further with `Pickup.Get()`\

No, i mean when i spawn pickup with `Pickup::CreateAndSpawn`, it tracked successfully and it added to list

**Comment by IRacle1** [comment]
can you show your code?

**Comment by IRacle1** [comment]
Fixed in #1902 and #1907
