### ISSUE TITLE
[BUG] Charging Jailbird Isallowed false breaks in inventory

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1958]
Description of bug: When denying the charging event for the jailbird it still in a way lets them charge up the jailbird you just cant run forward and attack and more importantly it breaks their inventory so they can no longer open it.

How to reproduce: IsAllowed = false in charging jailbird event and then attempting to charge jailbird

**Comment by ALEXWARELLC** [comment]
> Description of bug: When denying the charging event for the jailbird it still in a way lets them charge up the jailbird you just cant run forward and attack and more importantly it breaks their inventory so they can no longer open it.
> 
> How to reproduce: IsAllowed = false in charging jailbird event and then attempting to charge jailbird

Adding on, you cannot drop the Jailbird either.
