### ISSUE TITLE
[BUG] Base game `Friendly Fire Detector` doesn't trigger Exiled ban events

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#1962]
**Describe the bug**
Base game `Friendly Fire Detector` doesn't trigger `BanningEventArgs` and `BannedEventArgs`

**Expected behavior**
It should trigger events

**EXILED Version ("latest" is not a version):**
[7.2.0](https://github.com/Exiled-Team/EXILED/tree/7.2.0)

**Comment by louis1706** [comment]
Confirmed it's happen with all Sever.Host ban
