### ISSUE TITLE
[BUG] NullReferenceException Exiled.Events

### ISSUE THREAD

**Issue by FinnFurwolf** [Exiled-Team/EXILED#1981]
**Describe the bug**
I have SCP-035 and Serpent's Hand plugin on my server. If you become SCP-035, you first spawn as Tutorial, what triggers another bug that gives you Serpent's Hand loadout. In some cases, it completely bugs out and just ends the round, no matter what teams are alive. This can also happen if Serpent's Hand spawns.
I first reported this to [SH](https://github.com/Exiled-Team/SerpentsHand/issues/45), but Developer of Serpent's Hand said, it's not a bug with his plugin, possibly CustomRoles.
Then I noticed this error message (see below).

**To Reproduce**
1. Small chance to happen if SH or SCP-035 spawns

**Expected behavior**
Round not ending

**Server logs**
[2023-08-01 00:55:15.669 +02:00] [ERROR] [Exiled.Events] Method "OnHurting" of the class "SerpentsHand.SerpentsHand" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler1[[Exiled.Events.EventArgs.Player.HurtingEventArgs, Exiled.Events, Version=7.2.0.0, Culture=neutral, PublicKeyToken=null]]" [2023-08-01 00:55:15.681 +02:00] [ERROR] [Exiled.Events] System.NullReferenceException: Object reference not set to an instance of an object at SerpentsHand.SerpentsHand.OnHurting (Exiled.Events.EventArgs.Player.HurtingEventArgs ev) [0x00014] in <7c51da7cb3be47b882a80e3f9b19d7a8>:0  at Exiled.Events.Extensions.Event.InvokeSafely[T] (Exiled.Events.Events+CustomEventHandler1[TInterface] ev, T arg) [0x00021] in :0

**EXILED Version ("latest" is not a version):**
7.2.0

**Results of `show plugins` command in console:**
[2023-08-01 13:28:51.757 +02:00] >>> show plugins
[2023-08-01 13:28:51.789 +02:00] Total number of plugins: 10
                                 Enabled plugins: 10
                                 Disabled plugins: 0
                                 
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 7.2.0.0
                                        - Required Exiled Version: 7.2.0.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 CustomAnnouncements:
                                        - Author: Build ported by Deeznuts
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: custom_announcements
                                        - Priority: Medium
                                 Scp035:
                                        - Author: Joker119
                                        - Version: 5.0.1.0
                                        - Required Exiled Version: 6.0.0
                                        - Prefix: Scp035
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 7.2.0.0
                                        - Required Exiled Version: 7.2.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 7.2.0.0
                                        - Required Exiled Version: 7.2.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Author: Exiled.Updater
                                        - Version: 3.1.2.0
                                        - Required Exiled Version: 7.2.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 7.2.0.0
                                        - Required Exiled Version: 7.2.0.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Serpents Hand:
                                        - Author: yanox, Michal78900 and Marco15453
                                        - Version: 6.3.0
                                        - Required Exiled Version: 7.1.0
                                        - Prefix: serpents_hand
                                        - Priority: Medium
                                 UIURescueSquad:
                                        - Author: JesusQC, Michal78900, maintained by Marco15453
                                        - Version: 5.3.0
                                        - Required Exiled Version: 7.1.0
                                        - Prefix: UIURescueSquad
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 7.2.0.0
                                        - Required Exiled Version: 7.2.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium

**Additional context**
Problem occurs very inconsistent.

**Comment by louis1706** [comment]
the error come from SerpentsHand.SerpentsHand not from Exiled
Ask for support on Exiled Plugin bug report

**Comment by FinnFurwolf** [comment]
Thanks for helping clarify the cause of the problem
