### ISSUE TITLE
[BUG] Fix Updater not updating Server when Exiled is Outdated & fix than other issue

### ISSUE THREAD

**Issue by louis1706** [Exiled-Team/EXILED#2065]
**Describe the bug**
- The updater will not be loaded if Exiled.Loader is outdated
- The Exiled.Updater will stop server to Dowload it's new version of Exiled (that make compltetely stop server)

**Expected behavior**
- it's should be able to udpater
- and should let people play the game while udpating server

**EXILED Version ("latest" is not a version):**
ExiledX -> Exiled 8.2

**Comment by snuubs** [comment]
Also having similar issue. Server loads fine and other players can join, but plugins do not load. Errors pasted below.



[Errors.txt](https://github.com/Exiled-Team/EXILED/files/12515725/Errors.txt)

**Comment by louis1706** [comment]
> Also having similar issue. Server loads fine and other players can join, but plugins do not load. Errors pasted below.
> 
> [Errors.txt](https://github.com/Exiled-Team/EXILED/files/12515725/Errors.txt)

that nothing to do with the Updater actually

**Comment by snuubs** [comment]
> > Also having similar issue. Server loads fine and other players can join, but plugins do not load. Errors pasted below.
> > [Errors.txt](https://github.com/Exiled-Team/EXILED/files/12515725/Errors.txt)
> 
> that nothing to do with the Updater actually

Do you know what the issue is? I haven't been able to figure it out. Never had this issue before until I ran the server for the first time after game update.

**Comment by louis1706** [comment]
Fixed next update
