### ISSUE TITLE
[Bug] Server does not load plugins correctly

### ISSUE THREAD

**Issue by snuubs** [Exiled-Team/EXILED#2086]
Describe the bug: Server will not run plugins as intended. 

To Reproduce: Run server as normal with plugins added.

Expected behavior: Server loads and players can join with plugins working 

Server Logs: https://pastebin.com/B2fV5FPC 

EXILED Version: 8.1.0

**Comment by VALERA771** [comment]
Don't really think that this is exiled bug. You probably using outdated plugins
