### ISSUE TITLE
[BUG] RoomBlackoutEventArgs doesn't call

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#2168]
**Describe the bug**
RoomBlackoutEventArgs doesn't call
Tested with that
![image](https://github.com/Exiled-Team/EXILED/assets/46756889/ac55feb8-4723-4fb6-9486-6659d18c46a2)

**EXILED Version ("latest" is not a version):**
 8.2.1

**Comment by louis1706** [comment]
[2023-10-27 19:15:05.486 +02:00] [DEBUG] [DevTools] [    Event: RoomBlackout]
                                   Player : 14 (Yamato) [76561198323183777@steam] *Scp SCPs Scp079 True*
                                   Scp079 : Scp SCPs Scp079 True
                                   Room : HczCrossing (HeavyContainment) [4] *1* |False|
                                   BlackoutDuration : 15
                                   AuxiliaryPowerCost : 25
                                   Cooldown : 17
                                   IsAllowed : True

**Comment by ALEXWARELLC** [comment]
Was this ever successfully solved?

**Comment by ITeMbI4** [comment]
Fixed
