### ISSUE TITLE
[Suggestion] Use GetModule for Stamina and Health

### ISSUE THREAD

**Issue by louis1706** [Exiled-Team/EXILED#2182]
.

**Comment by ALEXWARELLC** [comment]
Not like this m guessing.
![image](https://github.com/Exiled-Team/EXILED/assets/123724383/5bd461ae-a5aa-4b77-adaf-8bba77bfc2da)

**Comment by ALEXWARELLC** [comment]
You may be able to link this issue to the PR.

**Comment by ALEXWARELLC** [comment]
Complete by #2171
