### ISSUE TITLE
[BUG] Broken health bar

### ISSUE THREAD

**Issue by Elektryk-Andrzej** [Exiled-Team/EXILED#2186]
![image](https://github.com/Exiled-Team/EXILED/assets/100864896/e7139850-9f7f-4edc-bd4e-0725a62af3ad)

**Describe the bug**
Will always show 100HP and the bar will go in the wrong direction as the health changes.

**To Reproduce**
1. Spawn

**Expected behavior**
HP should update and bar should go in the right direction based on hp

**Server logs**
part 1 https://pastebin.com/N2xAFnf9
part 2 https://pastebin.com/eudK4hXp

**EXILED Version 8.3.2:**

**Results of `pluginmanager show` command in console:**
Enabled plugins: 7
Disabled plugins: 0

Exiled.Events:
      - Author: Exiled Team
        - Version: 8.3.2.0
        - Required Exiled Version: 8.3.2.0
        - Prefix: exiled_events
        - Priority: Highest
 ScriptedEvents:
        - Author: Thunder + Johnodon
        - Version: 2.4.1
        - Required Exiled Version: 8.2.1
        - Prefix: scripted_events
        - Priority: High
 Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 8.3.2.0
        - Required Exiled Version: 8.3.2.0
        - Prefix: exiled_custom_items
        - Priority: Medium
 MapEditorReborn:
        - Author: Michal78900
        - Version: 3.0.1
        - Required Exiled Version: 8.3.2
        - Prefix: map_editor_reborn
        - Priority: Medium
 Exiled.CustomRoles:
        - Author: Exiled Team
        - Version: 8.3.2.0
        - Required Exiled Version: 8.3.2.0
        - Prefix: exiled_custom_roles
        - Priority: Medium
 Exiled.Permissions:
        - Author: Exiled Team
        - Version: 8.3.2.0
        - Required Exiled Version: 8.3.2.0
        - Prefix: exiled_permissions
        - Priority: Medium
 Exiled.CreditTags:
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 8.3.2.0
        - Required Exiled Version: 8.3.2.0
        - Prefix: exiled_credits
        - Priority: Medium

**Comment by Misaka-ZeroTwo** [comment]
@Elektryk-Andrzej Should be working now?

**Comment by Elektryk-Andrzej** [comment]
Yes, it now works like it should 👍
