### ISSUE TITLE
[BUG] SearchingEvent

### ISSUE THREAD

**Issue by louis1706** [Exiled-Team/EXILED#2324]
**Describe the bug**
Exiled make unable to change the searching time for pickup

**To Reproduce**
1. Use NW event to modify the time to search a pickup
2. it's do not work if exiled SearchingPickupEvent is used (transpiler)

**Expected behavior**
Exiled should not impact on how NWEvent work

**Comment by VALERA771** [comment]
Can't find NW event where we can change this. Can you name it pls cuz maybe patch method problem

**Comment by louis1706** [comment]
> Can't find NW event where we can change this. Can you name it pls cuz maybe patch method problem

Plugin was modifying the Weight of the item and nw event is call when whe use this ``searchCompletor.ValidateStart()``
in base game ValidateStart is call before ``request.Target.SearchTimeForPlayer(Hub)```but Exiled make it call after 

also we don't need to remove the the first line of code and we can keep IsAllowed as always true

**Comment by louis1706** [comment]
#2311 my original PR but i have need to abandon it since my computer broke

**Comment by VALERA771** [comment]
Not reproducible
