### ISSUE TITLE
Example project is too overwhelming

### ISSUE THREAD

**Issue by okunamayanad** [Exiled-Team/EXILED#2331]
The example project is for people who are new to making an EXILED plugin. It shouldn't be something that uses this much aspects of the API. It should be like a template that everybody can easily understand and work on top of it

**Comment by VALERA771** [comment]
I don't really think that it'll be hard to understand. Of course, you need to know C#. If it's still too hard, you can start with reading [For Developers](https://github.com/Exiled-Team/EXILED#for-developers) section in readme or [Getting started](https://github.com/Exiled-Team/EXILED/blob/master/GettingStarted.md) page from docs (better to read both of them).

**Comment by okunamayanad** [comment]
In my opinion an example project should be a template that could fit into every project, for EXILED it can be a plugin that logs "Hello world!" on enable. I understand the way Exiled took with the example project. I'm not saying that the example project isn't understandable, just saying that this way it could be more useful.

**Comment by VALERA771** [comment]
It includings all usable features. So we don't have lots of examples for every part of existing APIs

**Comment by An4r3w** [comment]
working on this, i'll make a pr soon

**Comment by IkaOverride** [comment]
Simplified in #2643

**Comment by ALEXWARELLC** [comment]
Consider closing this Issue, if the issue has been resolved.

**Comment by okunamayanad** [comment]
Looks like resolved in #2643, closing the issue.
