### ISSUE TITLE
[FEATURE REQUEST] Allow use of non-default paths

### ISSUE THREAD

**Issue by Greelan** [Exiled-Team/EXILED#2371]
I'm using a` hoster_policy.txt` file to force SCP:SL to create an AppData directory alongside the server binary, and look for configs, plugins etc there. This was recommended by Northwood as a way of consolidating files for the purpose of using a hosting panel.

EXILED does not honour it tho. If I install the files manually in AppData, it runs from there fine, but creates its configs still (plus reinstalls its deps) in `%AppData%\Roaming `or `~/.config`.

I see that `Paths.cs` hardwires the location. Is it possible to introduce some flexibility here to specify an alternative path for EXILED to use, say through an environment variable?

**Comment by joker-119** [comment]
You see Paths.cs hardwires the locations, but  you failed to see the config value for Exiled.Loader that allows you to change the directory path to something else.

**Comment by Greelan** [comment]
OK, useful to know, thanks. I assume you are referring to `ExiledDirectoryPath`?

Now, how to use it? Do I need to use the installers for this to be configured, or can I do it with manual installation?

**Comment by VALERA771** [comment]
You can manually install, change path and then move everything from /EXILED to your new path

**Comment by Greelan** [comment]
Yeah, I've figured it out.

In `AppData/SCP Secret Laboratory/PluginAPI/plugins/global/Exiled Loader/config.yml`, I can change `exiled_directory_path` to `AppData/EXILED`
