### ISSUE TITLE
[BUG] Exiled.Events unsubscibes a wrong Map.Generated event in OnDisabled

### ISSUE THREAD

**Issue by 4310V343k** [Exiled-Team/EXILED#2377]
## Describe the bug

OnEnabled:
https://github.com/Exiled-Team/EXILED/blob/c6945d8901df9446eb4844855e58ef4c2a89b7bf/Exiled.Events/Events.cs#L62

OnDisabled:
https://github.com/Exiled-Team/EXILED/blob/c6945d8901df9446eb4844855e58ef4c2a89b7bf/Exiled.Events/Events.cs#L94

## Additional context
[Someone](https://github.com/Exiled-Team/EXILED/commit/885d39a5e09ea2d7b19196d1fa432a8dcb1afe7f#diff-231a7143678f2376fbab9bdd2f51b5aeefa2905d9a0f47f812c84bf6ccaf506e) probably added an internal event, replaced the old one with it in OnEnabled and simply forgot to do the same in OnDisabled
I'm not sure which actual issues may arise from that, but it's clearly wrong *and* I'm too lazy to fix it, so... Here, have this issue instead

**Comment by louis1706** [comment]
thanks for the Report i will see to fix this issue than nobody see lol
