### ISSUE TITLE
[BUG] [DynamicEvents] Scp914.UpgradingInventoryItem event does not fire unless Scp914.UpgradingPlayer is subscribed.

### ISSUE THREAD

**Issue by o5zereth** [Exiled-Team/EXILED#2452]
Simply subscribing to the Scp914.UpgradingInventoryItem event is not sufficient to receive it properly.
The harmony patch involved with firing this event is only attached to the Scp914.UpgradingPlayer event, and requires that it be subscribed to as well before Scp914.UpgradingInventoryItem can be fired as intended.

**Comment by louis1706** [comment]
Thanks for the Information next release will contain the fix (for now you can get the build directly from github) on #2455
