### ISSUE TITLE
[SUGGESTION] Update harmony, use built-in PatchCategory

### ISSUE THREAD

**Issue by moddedmcplayer** [Exiled-Team/EXILED#2537]
title

**Comment by moddedmcplayer** [comment]
A lot of the stuff in https://github.com/Exiled-Team/EXILED/blob/dev/Exiled.API/Features/GlobalPatchProcessor.cs and https://github.com/Exiled-Team/EXILED/blob/master/Exiled.Events/Features/Patcher.cs is now part of harmony itself, see https://harmony.pardeike.net/articles/basics.html#patching-using-annotations.

**Comment by ALEXWARELLC** [comment]
@NaoUnderscore Any plans to use `PatchCategory`?
