### ISSUE TITLE
[BUG] [API-Rework] Server Crashing On Spawning

### ISSUE THREAD

**Issue by xNexusACS** [Exiled-Team/EXILED#2549]
**Describe the bug**
The server just crashes when spawning at the start of the round.

**To Reproduce**
1. Force Round Start or Start the round normally
2. Check the exception in LALogs xd

**Expected behavior**
Should spawn normally without crashing.

**Server logs**
https://pastebin.com/wTPLQTfE

**EXILED Version ("latest" is not a version):**
API Rework Branch

**Comment by VALERA771** [comment]
Seems like error in base game code

**Comment by xNexusACS** [comment]
> Seems like error in base game code which we don't patch. So does it really happens always and is it an EXILED bug?

check the exception better: 
```
[2024-05-06 18:46:34.639 +02:00] [STDOUT]   at Exiled.Events.Patches.Events.Player.Spawning.Prefix (ReferenceHub hub, PlayerRoles.PlayerRoleBase prevRole, PlayerRoles.PlayerRoleBase newRole) [0x0008b] in <dc4258c036e64032b9da797bfb7b22c2>:0
```

**Comment by VALERA771** [comment]
Yeah, I saw. But the exact place where exception happens is in base game code

**Comment by xNexusACS** [comment]
> Yeah, I saw. But the exact place where exception happens is in base game code

ik, is a little bit rare tbh

**Comment by VALERA771** [comment]
Can you say on which role you were force classing when you got this error? Or you'd just started round?

**Comment by xNexusACS** [comment]
> Can you say on which role you were force classing when you got this error? Or you'd just started round?

just started the round normally (I was the only player in the server)

**Comment by louis1706** [comment]
> > Can you say on which role you were force classing when you got this error? Or you'd just started round?
> 
> just started the round with the RA (I was the only player in the server)

i need to have more info on it 

do you know wish player / RoleTypeId his trying to spawn ?

**Comment by Misfiy** [comment]
if theyre solo on the server with default configs, itd be classD

**Comment by ALEXWARELLC** [comment]
I'll get this tested tomorrow.

**Comment by xNexusACS** [comment]
> @xNexusACS Were you able to reproduce this bug on the latest version of EXILED or does it still occur?

I didn't tried the new latest alpha, so im not really sure if it still happens there

**Comment by Misfiy** [comment]
Cannot reproduce on any exiled 9 alpha, appears fixed
