### ISSUE TITLE
Will Exiled.CreditTags be removed?

### ISSUE THREAD

**Issue by ALEXWARELLC** [Exiled-Team/EXILED#2562]
After the CreditTags system was broken after the loss of the server hosting the backend, will CreditTags be fixed or will it be removed?

**Comment by VALERA771** [comment]
I don't think so. As exiled is now in partnership with terabit (as on website said iirc). Also there is platform where we host discord bot on which we can place db (I think so. Don't blame if I'm not right pls)

**Comment by louis1706** [comment]
Exiled.CreditsTags will be fixed when Nao will have time for it

**Comment by ALEXWARELLC** [comment]
I'll close this issue due to a lack of activity & due to CreditTags being rewritten.
