### ISSUE TITLE
[BUG] Exiled.Installer ignores absence of pre-release flag.

### ISSUE THREAD

**Issue by joker-119** [Exiled-Team/EXILED#2570]
**Describe the bug**
When downloading an update, if --pre-releases is not defined in the startup arguments, it still downloads pre-releases.

```Joker@fedora:~$ ./Exiled.Installer-Linux
Exiled.Installer-Linux-4.0.0.0
AppData folder: /home/Joker/.config
Exiled folder: /home/Joker/.config
Receiving releases...
Prereleases included - False
Target release version - (null)
Searching for the latest release that matches the parameters...
Trying to find release..
Release found!
PRE: True | ID: 156417851 | TAG: 8.9.2
Asset found!
ID: 168834447 | NAME: Exiled.tar.gz | SIZE: 1155692 | URL: https://api.github.com/repos/Exiled-Team/EXILED/releases/assets/168834447 | DownloadURL: https://github.com/Exiled-Team/EXILED/releases/download/8.9.2/Exiled.tar.gz
```

**To Reproduce**
1. Download installer.
2. Run installer without --pre-release argument
3. See that it still downloads a pre-release.

**Expected behavior**
A pre-release should not be downloaded when the --pre-release argument is not used, as this breaks server automation scripts.

**Server logs**
N/A

**EXILED Version ("latest" is not a version):**
8.8.1

**Results of `pluginmanager show` command in console:**
N/A

**Additional context**
Plz fix my customers are highly confused by the brainletness of this bug.

**Comment by louis1706** [comment]
Fixed
