### ISSUE TITLE
[BUG] SanitizeResponse doesn't get generated with ICommand.

### ISSUE THREAD

**Issue by ALEXWARELLC** [Exiled-Team/EXILED#2638]
**Describe the bug**
```cs
public bool SanitizeResponse;
```

The above line of code is not generated with the ICommand interface. Even though it's required for any ICommand command to compile.

**To Reproduce**
1. Create a new class with `ICommand`
2. Right-Click and click `Implement Interface`
4. `ICommand` gives off an error.

**Expected behavior**
`ICommand` shouldn't give an error & `SanitizeResponse` should be generated.

**EXILED Version 8.9.6**

**Comment by Misfiy** [comment]
Unrelated to EXILED and cannot be fixed by EXILED.
