### ISSUE TITLE
[BUG] Exiled.tar.gz packed as RAR archive, not gzip tarball

### ISSUE THREAD

**Issue by Greelan** [Exiled-Team/EXILED#2792]
**Describe the bug**
The latest release of Exiled.tar.gz is not a valid gzip tarball:

```
$ file Exiled.tar.gz
Exiled.tar.gz: RAR archive data, v5
```

**To Reproduce**
1. `wget https://github.com/Exiled-Team/EXILED/releases/download/8.9.11-halloween/Exiled.tar.gz`
2. `tar -xzvf Exiled.tar.gz`
3. Get error: 
   ```
   gzip: stdin: not in gzip format
   tar: Child returned status 1
   tar: Error is not recoverable: exiting now
   ```

**Expected behavior**
The archive is in the correct format and able to extracted by tar as per the instructions.

**Server logs**
Not relevant

**EXILED Version ("latest" is not a version):**
Not relevant

**Results of `pluginmanager show` command in console:**
Not relevant

**Additional context**
N/A

**Comment by xNexusACS** [comment]
fixed for the next release (8.9.12 & Beta 7)
