### ISSUE TITLE
my autolog

### ISSUE THREAD

**Issue by Tamago4a** [Exiled-Team/EXILED#311]
My coder said the error was related to exiled itself.
[MA_logs_14_11_2020_09_59_35.txt](https://github.com/galaxy119/EXILED/files/5540788/MA_logs_14_11_2020_09_59_35.txt)

**Comment by iRebbok** [comment]
That's an issue from the main game. Also on our Tello -> https://trello.com/c/WbGiY4vE.
I commented on this on August 6th, but fixing this seems problematic.

**Comment by Tamago4a** [comment]
> That's an issue from the main game. Also on our Tello -> https://trello.com/c/WbGiY4vE.
> I commented on this on August 6th, but fixing this seems problematic.

What is this anyway? How does it affect the game? How to cause this error?

**Comment by iRebbok** [comment]
Check out the comments on the card on our Trello.
