### ISSUE TITLE
Feature: Standardize output of plugin loading

### ISSUE THREAD

**Issue by Kowaman** [Exiled-Team/EXILED#385]
When a server starts up, it seems plugins send their own messages to mark they are enabled, making it difficult for debugging when installing new plugins. EXILED should output a list of all plugins as they are loaded/enabled.

Please forgive me if this request is nonsense as I am unfamiliar with plugin development for EXILED as well as C#.

**Comment by iopietro** [comment]
You can use the `show plugins` command to see the plugins list.

**Comment by iRebbok** [comment]
@Kowaman what do you mean exactly? Those methods are virtual, you can call a base method or skip it. Also we already have the `show plugins` command to see enabled/disabled plugins and etc.
