### ISSUE TITLE
SCP-106 cannot capture players running 2.6.1-beta (Exiled.Events.dll)

### ISSUE THREAD

**Issue by PatPeter** [Exiled-Team/EXILED#431]
I just spend the past 2 hours deleting every single plugin from my server, and finally I figured out that if I deleted Exiled.Events.dll, SCP-106 could capture members again, but if I keep Exiled.Events.dll on the server even by itself, he can't capture anyone.

I would try downgrading to 2.5.0 but it has no download. I also tried 2.4.4-beta and the game process went on a crash loop.

**Comment by galaxy119** [comment]
I'm not able to reproduce this, make sure you don't have any plugins that could interfere with 106's capturing.

**Comment by galaxy119** [comment]
https://youtu.be/CW0KF0MdVOI

**Comment by galaxy119** [comment]
Remove plugin: SCP-035 until it is updated.

**Comment by PatPeter** [comment]
Sorry for the bad report. I was limited on time when I was testing last night and it seems we missed removing SCP-035 as a test case.
