### ISSUE TITLE
customitems damage ignores 106 protection

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/EXILED#448]

**Comment by ZWRh3** [comment]
im not 100% sure since it happened on kings playground and the server is having extreme bugs right now

**Comment by galaxy119** [comment]
To remedy:
virtual CustomWeapon.OnHurting should check if the target is RoleType106 and calculate damage accordingly before setting ev.Amount.

**Comment by galaxy119** [comment]
Fixed in dev branch, to be included in next pre-release.
