### ISSUE TITLE
pickup_text and select_text (CustomItems API)

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/EXILED#457]
editing the pick up text and the selection text is usefull for:
non english servers
having the correct article (a/an)

**Comment by iopietro** [comment]
What do you mean? Those texts are already customizable.

**Comment by galaxy119** [comment]
https://github.com/Exiled-Team/EXILED/blob/master/Exiled.CustomItems/Config.cs#L29

https://github.com/Exiled-Team/EXILED/blob/master/Exiled.CustomItems/Config.cs#L35
