### ISSUE TITLE
grenade chain explosions are broken

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/EXILED#462]
custom grenades spawn as as if they were thrown as oposed to the normal instant chain explosions and normal grenades dont have chain explosions at all

**Comment by galaxy119** [comment]
Grenades don't normally "instant explode" when hit with other grenades. They are turned into active grenades in the same way custom grenades do now when hit with an explosion. 

As for chains not working on normal grenades, I will look into this.

**Comment by galaxy119** [comment]
Fixed in 3c35ff16fd418c29db01b8e28c848ef89c6cf8ca
