### ISSUE TITLE
Anonymizing UserID's broke Exiled.CreditTags

### ISSUE THREAD

**Issue by Michal78900** [Exiled-Team/EXILED#502]
On EXILED 2.10.0, where the changes from this #467 PR were applied, `Exiled.CreditTags` does not work at all. Authorized players don't get their role, nor the `.crtag` command work. This isn't a issue on EXILED 2.9.4 and below.

There are 2 solutions (which I see) to fix this problem:

- Remove the changes from #467 PR which is the easier method, but Northwood would be mad for not hashing **public** UserIds.
- Make the site properlly read the hashed UserId and return the credit role.

![image](https://user-images.githubusercontent.com/75911188/119561758-df631c00-bda5-11eb-8448-ef837ccedbeb.png)

**Comment by Michal78900** [comment]
The issue seems to be resolved. If nothing bad happens I will close the issue.

**Comment by Michal78900** [comment]
Yeah, seems to be working right now, thank you for fixing this issue.

**Comment by PintTheDragon** [comment]
> At this very second, no, but once this PR is approved, I will be updating the backend to be able to respond to either raw userid's like it currently does, or userid hashes.
@joker-119 :hmmmm:
