### ISSUE TITLE
"Pickup" is in Assembly but not referenced

### ISSUE THREAD

**Issue by Kino7916** [Exiled-Team/EXILED#509]
I'm trying EXILED Framework and doing my own version of the Tranquelizer Gun, but I'm not sure why I got this not referenced.
I installed the framework via DotNet, any solutions that I can get?

![Screenshot_1090](https://user-images.githubusercontent.com/73807155/121999497-97994880-cdd7-11eb-8f9e-f855f1efc0a2.png)

**Comment by InsetJesux** [comment]
This is not an issue, you must add a reference to 'Assembly-CSharp'.

**Comment by Kino7916** [comment]
Oh, I tried the solution, thanks :D
