### ISSUE TITLE
.scpswap command personally broken

### ISSUE THREAD

**Issue by Tordak** [Exiled-Team/EXILED#539]
A warning, I'm completely illiterate when it comes to code, but have no where else to turn.

I've been having issues with the scp swap command, in that it only returns an error message.
I'll type in: .scpswap 079, where after the server will return

(01:28:50.836] Sending command to server: scpswap 079
[01:28: 50.878] [FROM SERVER] SCPSWAP# Command execution failed! Error:
System. ArgumentNullException: Value cannot be null.
Parameter name: key
at System.Collections.Generic.Dictionary 2[TKey, TValue). FindEntry (Tkey key)
[0x00008] in <9577ac7a62ef43179789031239ba8798>:0
at System.Collections.Generic.Dictionary 2[TKey, TValue]. Containskey (Tkey key)
[0x00000] in <9577ac7a62ef43179789031239ba8798>:0
at ScpSwap.Commands. ScpSwapCommand. ScpSwapCommand.ExecuteParent
(System. ArraySegment 1[1] arguments, Command System. ICommandSender sender,
System.String& response) [0x00066] in <648a0549c9a543eb964839ea0b6eaaff>:0
at ParentCommand.Execute (System. ArraySegment '1[1] arguments,
Commandsystem. ICommandSender sender, System.String& response) [0x00049] in
<445724aca0854baf9bac580cf29e2327>:0
at (wrapper dynamic-method)
RemoteAdmin. QueryProcessor. RemoteAdmin.QueryProcessor.ProcessGameConsoleQuery_Pat
ch1 (RemoteAdmin. QueryProcessor, string, bool)

I've tried asking for other scp's to send me a swap request. That works up until I have to accept the swap
.scpswap yes
After that, the server tells me I don't have any swap requests

This is an ongoing issue that happens on all servers I join. I haven't edited my game files, I verified them, and still have had no success. Help?

**Comment by joker-119** [comment]
Report this to SCP Swap, not us.
