### ISSUE TITLE
Very rare, but happens

### ISSUE THREAD

**Issue by joker-119** [Exiled-Team/EXILED#541]
[Le map gen error](https://cdn.discordapp.com/attachments/664263236048388097/864042695991230494/unknown.png)

**Comment by PintTheDragon** [comment]
I mean, sure it should be fixed, but like realistically, does this actually ever happen?

**Comment by joker-119** [comment]
![image](https://user-images.githubusercontent.com/10914157/126998069-b3a6910f-0ed9-4358-9c86-5ed3021b1b2d.png)

**Comment by PintTheDragon** [comment]
Actually, while I don't believe that this actually happens from seed generation, I assume this happens whenever someone sets the map seed in configs.

**Comment by PintTheDragon** [comment]
I was trolled. This has to do with having duplicate cameras if I think.

**Comment by joker-119** [comment]
Fixed in 3.0
