### ISSUE TITLE
Make all strings in the config be serialized with single quotes

### ISSUE THREAD

**Issue by PintTheDragon** [Exiled-Team/EXILED#563]
One issue I've seen is that some people might edit a string in a config, and it creates a parsing error because they forgot to surround it with single quotes. Or, some properties have quotes, while some just don't. I think it would be much better to just not serialize strings without quotes around them (of course, excluding weird yaml stuff like multi-line strings). I'm not too sure how this can be done in YamlDotNet though.

So essentially, everything should look like:
```
prop1: 'message'
prop2: '<color=wow>wow</color>'
```
and not
```
prop1: message
prop2: '<color=wow>wow</color>'
```

Just to reduce the amount of config parsing errors that we get.

**Comment by Jesus-QC** [comment]
https://github.com/aaubry/YamlDotNet/issues/315#issuecomment-380361996

**Comment by Jesus-QC** [comment]
dont have time to implement it rn, will leave that there

**Comment by PintTheDragon** [comment]
> [aaubry/YamlDotNet#315 (comment)](https://github.com/aaubry/YamlDotNet/issues/315#issuecomment-380361996)

I've looked into this, although it seems like it wraps both keys and values in strings.

**Comment by joker-119** [comment]
Ew

**Comment by louis1706** [comment]
#1808
