### ISSUE TITLE
Exiled.API.Extensions.MirrorExtensions.PlayCassieAnnouncement only on the First Round

### ISSUE THREAD

**Issue by qjy330** [Exiled-Team/EXILED#571]
Exiled.API.Extensions.MirrorExtensions.PlayCassieAnnouncement only on the First Round

if round restart(fast restart or normal),Exiled.API.Extensions.MirrorExtensions.PlayCassieAnnouncement throw Exception.
must in the full restart,Exiled.API.Extensions.MirrorExtensions.PlayCassieAnnouncement can use in first round

**Comment by joker-119** [comment]
What is the exception it throws, please?

**Comment by qjy330** [comment]
i don't know ,the console is not print.
i can't catch the throws in the exiled.api.dll

**Comment by qjy330** [comment]
i hope you test this problem. i have a story plugin use this void,but now it always fails.
i check the Assembly-CSharp.dll,the RespawnEffectsController.AllControllers is private.
could that be the reason?
