### ISSUE TITLE
Automatic command reloading on config/translations reload

### ISSUE THREAD

**Issue by PintTheDragon** [Exiled-Team/EXILED#576]
One of the reasons that translations were added was to make it easier for plugins to provide server owners with the ability to configure their commands and aliases. This works fine, but if the plugin simply uses it as a normal config value, the plugins must be reloaded after a config reload for new commands/aliases to take effect.

To solve this, plugins can do something such as this:
```csharp
private void OnReloadedTranslations()
{
    this.OnUnregisteringCommands();
    this.OnRegisteringCommands();
}
```
Which will reload their commands on translations reload.

So, should we automatically do this on configs/translations reload, to make configurable commands easier for plugins? Right now, I can't really think of any downsides, aside from unnecessary reloading (but it does only happen on `rld configs`/`rld translations`), so I'd love to hear other people's opinion on something like this.

**Comment by joker-119** [comment]
I agree, this should be done automatically by EXILED, and I also don't really see a downside to it either. We're talking about making the reload process take a few ns longer, but it's only during reloads, the time added is negligible.
