### ISSUE TITLE
Cassie Doing "s-" after most of the words.

### ISSUE THREAD

**Issue by BlackstrikeSK** [Exiled-Team/EXILED#597]
So, I wanted to make a cassie announcement, but cassie adds an "s-" to most of the words, they are valid, I checked, those that weren't valid were replaced. I'd like a fix for it a lot.

Thanks a lot!

https://user-images.githubusercontent.com/60195039/130513989-6e0a1602-c150-4d65-a3f7-9943473d58b6.mp4

**Comment by Michal78900** [comment]
Can you give the list of the words you used and tell us if this issue also occurs on the server without EXILED?

**Comment by joker-119** [comment]
Cassie.Message is literally just an alias for `RespawnEffectsController.PlayCassieAnnouncement` which is a base-game method. If you copy/paste the message string into the in-game cassie command does it not still do this?

**Comment by BlackstrikeSK** [comment]
I'll try later today and give you an reply

**Comment by BlackstrikeSK** [comment]
yes, it does it without the EXILED

**Comment by Michal78900** [comment]
Not an EXILED issue then
