### ISSUE TITLE
[Recomendation] Use new codespaces to contribute to EXILED

### ISSUE THREAD

**Issue by xRoier** [Exiled-Team/EXILED#734]
# What is GitHub Codespaces?
Codespaces is a cloud-based development environment based on VS Code. Instead of installing an editor and dependencies locally, you can access a cloud-based development environment that contains all the tools needed to be productive with the repo. You can learn more about Codespaces at https://docs.github.com/en/codespaces/about-codespaces.

# How do I get access to Codespaces?
You'll have to sign up for the Codespaces beta at https://github.com/features/codespaces/signup.

![imagen_2021-09-21_201730](https://user-images.githubusercontent.com/58123692/134225647-3366536d-48c6-4ff2-9e47-615122a41092.png)

This would be cool to implement so we can contribute without editor and without downloading/updating the dependencies every time

**Comment by PintTheDragon** [comment]
I signed up for codespaces beta a bit ago, still haven't gotten in. It's a cool idea, but seems expensive to use.

**Comment by joker-119** [comment]
This this is ganna be a hard pass for me.
