### ISSUE TITLE
[BUG] Uncuffing event doesn't tell you who's actually uncuffing them.

### ISSUE THREAD

**Issue by joker-119** [Exiled-Team/EXILED#736]
See: https://github.com/Exiled-Team/DiscordIntegration/issues/64

**Comment by joker-119** [comment]
No it has not. If player A cuffs B and then player C uncuffs B, the uncuffing event will say that A is uncuffing B

**Comment by NaoUnderscore** [comment]
Oh, this makes sense then. I tried with two SCP:SL instances, that's why it worked for me.
I'll fix this shit if you want.
