### ISSUE TITLE
[BUG] Player.Zone in Surface gives you Zonetype.Unspecified

### ISSUE THREAD

**Issue by zhaguanyang** [Exiled-Team/EXILED#826]
**EXILED Version ("latest" is not a version):**
3.3.1

**Comment by zhaguanyang** [comment]
Previously mentioned in https://discord.com/channels/656673194693885975/664263236048388097/902832491625316413

**Comment by zhaguanyang** [comment]
Tested and it happens every time

**Comment by joker-119** [comment]
Can you please test to verify whether this bug has been fixed in 3.4.0-beta?

**Comment by zhaguanyang** [comment]
![image](https://user-images.githubusercontent.com/45165615/140304447-57134de5-df73-4710-8d27-9b01dad97a86.png)
Nope

**Comment by zhaguanyang** [comment]
![image](https://user-images.githubusercontent.com/45165615/140304675-8967a8bf-f14c-4826-bfeb-67eabbb17706.png)

**Comment by zhaguanyang** [comment]
Not sure if this is caused by the Halloween update, I am sure this thing works before Halloween

**Comment by joker-119** [comment]
It's possible nw broke the surface areas zone type in 11.0, I will do since testing in a few hours to find out the issue

**Comment by zhaguanyang** [comment]
Yeah, not cause by halloween. Still having this issue today

**Comment by NaoUnderscore** [comment]
This bug has been fixed. See #864.
