### ISSUE TITLE
[BUG] Weapon Multiplers for Throwables.

### ISSUE THREAD

**Issue by Oxygen556** [Exiled-Team/EXILED#833]
Weapon Damage Multipliers don't affect explosive grenades or SCP-018 ever since the parabellum update.

I've attached a screenshot of how I have my menu configured. I've cranked it up to 5 to see if there's any significant change, but the damage stays at vanilla levels. (Apologies for the congested view.)

![Screenshot_20211101-080005_Chrome](https://user-images.githubusercontent.com/92807576/139669208-c413f83f-618a-4278-9855-526ec41f4fce.jpg)

Currently running version 3.3.1 of EXILED.

**Comment by joker-119** [comment]
This isn't an EXILED issue, please report this to the plugin that adds this config option.
