### ISSUE TITLE
[BUG] Broken TogglingFlashlight event

### ISSUE THREAD

**Issue by Liassid** [Exiled-Team/EXILED#840]
**Describe the bug**
Toggling a flashlight in waiting for players stage kicks the player/freezes the server

**To Reproduce**
1. Equip a flashlight in a lobby and try to toggle it
2. Either you are kicked or server freezes

**Expected behavior**
Flashlight can be toggled normally

**Server logs**
N/A

**EXILED Version ("latest" is not a version):**
3.2.0

**Results of `show plugins` command in console:**

```
Total number of plugins: 7
Enabled plugins: 5
Disabled plugins: 2

Exiled.Events:
        - Author: Exiled Team
        - Version: 3.2.0.0
        - Required Exiled Version: 3.2.0.0
        - Prefix: exiled_events
        - Priority: Highest
WaitAndChillReborn:
        - Author: Michal78900
        - Version: 3.1.0
        - Required Exiled Version: 3.2.1
        - Prefix: wait_and_chill_reborn
        - Priority: Medium
Exiled.Updater:
        - Disabled
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 3.2.0.0
        - Prefix: exiled_updater
        - Priority: Medium
Exiled.CreditTags:
        - Disabled
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 3.4.0.0
        - Required Exiled Version: 3.2.0.0
        - Prefix: exiled_credits
        - Priority: Medium
Exiled.CustomRoles:
        - Author: Exiled Team
        - Version: 3.4.0.0
        - Required Exiled Version: 3.2.0.0
        - Prefix: exiled_custom_roles
        - Priority: Medium
Exiled.Permissions:
        - Author: Exiled Team
        - Version: 3.4.0.0
        - Required Exiled Version: 3.2.0.0
        - Prefix: exiled_permissions
        - Priority: Medium
Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 3.4.0.0
        - Required Exiled Version: 3.2.0.0
        - Prefix: exiled_custom_items
        - Priority: Medium
```

**Comment by joker-119** [comment]
Cannot replicate the issue:
https://youtu.be/2avJG9jOwCA

**Comment by Liassid** [comment]
The issue occured on this version: https://github.com/Exiled-Team/EXILED/releases/tag/3.4.0-beta

**Comment by joker-119** [comment]
That's the version I am running aswell.

I used the DevTools plugin to log events, and WaitAndChillReborn to spawn in during the waiting for players lobby screen.

I gave myself a flashlight, and turned it off and on repeatedly. I experienced no errors in the server console or logs, nor the described behavior of the client disconnecting or the server freezing.
