### ISSUE TITLE
[BUG] Setting player's CurrentItem leads to issues

### ISSUE THREAD

**Issue by Liassid** [Exiled-Team/EXILED#851]
**Describe the bug**
If item is set by CurrentItem, it behaves differently than if player had equipped an item themselves. For example, flashlight won't stop SCP-173, toggling such flashlight in a lobby will disconnect a player, shotgun will malfunction.

**To Reproduce**
1. Set player's item to a flashlight
2. Turn off lights in the room
3. SCP-173 can move freely (reequip fixes this issue)

**Expected behavior**
Item behaves as it should

**Server logs**
N/A

**EXILED Version ("latest" is not a version):**
3.6.0-beta

**Results of `show plugins` command in console:**
N/A

**Comment by Liassid** [comment]
https://github.com/Exiled-Team/EXILED/issues/840

**Comment by Liassid** [comment]
https://youtu.be/Ka6B9m60Qso

**Comment by NaoUnderscore** [comment]
Issue #840 Doesn't have anything to do with this issue.

**Comment by joker-119** [comment]
does this still occur? I don't see any reason it should, CurrentItem just calls the method the server already uses when a player selects the item themselves.

**Comment by Liassid** [comment]
Yup, just checked and it still happens

**Comment by Liassid** [comment]
Also toggling such flashlight causes "server was forced to stop the connection". Dropping and picking up that flashlight fixes the issue. It also doesn't happen if the flashlight is given through RA.

```
[STDOUT] Exception in MessageHandler: InvalidCastException Specified cast is not valid.
[STDOUT]   at Exiled.Events.EventArgs.TogglingFlashlightEventArgs..ctor (Exiled.API.Features.Player player, InventorySystem.Items.Flashlight.FlashlightItem flashlight, System.Boolean newState, System.Boolean isAllowed) [0x00014] in <44005ff74d8440a0a463348507a9a654>:0
[STDOUT]   at (wrapper dynamic-method) InventorySystem.Items.Flashlight.FlashlightNetworkHandler.InventorySystem.Items.Flashlight.FlashlightNetworkHandler.ServerProcessMessage_Patch0(Mirror.NetworkConnection,InventorySystem.Items.Flashlight.FlashlightNetworkHandler/FlashlightMessage)
[STDOUT]   at (wrapper delegate-invoke) System.Action`2[Mirror.NetworkConnection,InventorySystem.Items.Flashlight.FlashlightNetworkHandler+FlashlightMessage].invoke_void_T1_T2(Mirror.NetworkConnection,InventorySystem.Items.Flashlight.FlashlightNetworkHandler/FlashlightMessage)
[STDOUT]   at Mirror.MessagePacking+<>c__DisplayClass4_0`2[T,C].<WrapHandler>b__0 (Mirror.NetworkConnection conn, Mirror.NetworkReader reader, System.Int32 channelId) [0x0006f] in <639b18746ebc4e7e905eeac9417c0a7a>:0
[STDOUT] (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Comment by joker-119** [comment]
Interesting.. perhaps there's something we need to do after doing the ServerSelectItem() call to sync everything up properly, thanks that helps.

**Comment by louis1706** [comment]
This it's fix in EXILED5.0 possibly already fix in older version
