### ISSUE TITLE
[BUG] ReportingCheater doesn't work

### ISSUE THREAD

**Issue by Liassid** [Exiled-Team/EXILED#861]
**Describe the bug**
ReportingCheater event doesn't fire

**To Reproduce**
1. Try to use "Report for cheating or raiding"

**Expected behavior**
Event is fired

**Server logs**
N/A

**EXILED Version ("latest" is not a version):**
3.6.2

**Results of `show plugins` command in console:**
N/A

**Additional context**
https://github.com/Exiled-Team/EXILED/pull/689

**Comment by NaoUnderscore** [comment]
I'd like you to test it on a verified server instead.

**Comment by NaoUnderscore** [comment]
This bug has been fixed. See #862.
