### ISSUE TITLE
[BUG] The `Player.Jumping` event only fires for SCP-173

### ISSUE THREAD

**Issue by Shirosaka** [Exiled-Team/EXILED#863]
**Describe the bug**
After toying around with the Jumping event for the purpose of counting the total jumps a player makes, I've ran into the bug that only SCP-173 will have the Jumping event fire for itself.

**To Reproduce**
1. Spawn in as any other class besides SCP-173
2. Jump
3. The Jumping event should fire

**Expected behavior**
The `Player.Jumping` event fires for every class.

**Server logs**
https://pastebin.com/QpUxA4jk

**EXILED Version ("latest" is not a version):**
EXILED 3.6.2

**Results of `show plugins` command in console:**
![grafik](https://user-images.githubusercontent.com/47280920/140903117-a30297c0-7494-4b82-bc82-9b698f99a8aa.png)

**Additional context**
None.

**Comment by NaoUnderscore** [comment]
This bug has been fixed. See #865.
