### ISSUE TITLE
[BUG] FF multipliers don't affect ev.Amount

### ISSUE THREAD

**Issue by Liassid** [Exiled-Team/EXILED#870]
**Describe the bug**
If you set some FF multiplier in gameplay config, the ev.Amount in Hurting event will be as if multiplier was 1

**To Reproduce**
1. Set some FF multiplier
2. Broadcast how many HP player should have after hurting
3. Shoot a teammate

**Expected behavior**
Damage multipliers affect ev.Amount

**EXILED Version ("latest" is not a version):**
3.6.2

![image](https://user-images.githubusercontent.com/53168424/141103326-48c54951-68a1-4fd6-a2f5-8833520b7802.png)

**Comment by NaoUnderscore** [comment]
I'm gonna handle this issue.
