### ISSUE TITLE
[BUG] Using Player::.RemoveHeldItem() while setting ev.IsAllowed = false in Shooting event leads to player getting kicked

### ISSUE THREAD

**Issue by Remuchi** [Exiled-Team/EXILED#873]
**Describe the bug**
As the title says. 

**To Reproduce**
`private void OnShooting(ShootingEventArgs ev)
{
   ev.Shooter.RemoveHeldItem();
   ev.IsAllowed = false;
}
`

**Expected behavior**
Player should not be kicked from server and his current item should be removed.

**Server logs**
https://pastebin.com/tcskF5me - SCP_Logs
https://pastebin.com/q952SrcU - MA_Logs

**EXILED Version: **
3.6.2

**Results of `show plugins` command in console:** 
Not needed.

**Additional context**
Adding delay between this 2 actions help remove the bug.

**Comment by NaoUnderscore** [comment]
Fixed in #875.
