### ISSUE TITLE
[BUG] Player.ArtificialHealth broken

### ISSUE THREAD

**Issue by zhaguanyang** [Exiled-Team/EXILED#931]
**Describe the bug**
Setting a player's artificial health is not going to have any effect.

**To Reproduce**
``Player.ArtificalHealth = 30f;``

**Expected behavior**
That player should gain 30 ahp

**EXILED Version ("latest" is not a version):**
4.1.2

**Comment by ITeMbI4** [comment]
Agree, also have this issue!

**Comment by joker-119** [comment]
That's because it hasn't been addressed yet (:
