### ISSUE TITLE
[BUG] 096 cancels rage if targets die early, time bonuses persist until next rage

### ISSUE THREAD

**Issue by Xypixian** [Exiled-Team/EXILED#959]
**Describe the bug**
If 096 gains targets while calm, but those targets all somehow die before 096 actually begins enraging, then 096s enrage will be cancelled.

However, for every target there was when this happens, 3 seconds of extra rage time will still be given to 096, which persist until he actually enrages properly. This can cause him to rage far longer than he should be allowed to if stacked enough times.

https://cdn.discordapp.com/attachments/664263236048388097/909037431418912808/2021-11-13_05-03-37.mp4

(in the clip, i cause the bug twice, and then i trigger him properly the third time around. 096 rages for 21 seconds instead of what should be 15.)

Tested in vanilla to make sure, and confirmed this is an exiled-specific issue.

**To Reproduce**
1. Have an 096.
2. Have a human player look at 096 and die (by any means) before 096 enters the Enraging state.
3. Witness 096 fail to rage.
4. Repeat step 2, but this time avoid dying beforehand.
5. Witness 096 rage successfully, but for an extended amount of time because of doing step 2. 

**Expected behavior**
096 rages when he is seen, regardless of whether or not his targets die. He rages for 15 seconds, with an additional 3 seconds for every target gained before he fully enrages.

**EXILED Version ("latest" is not a version):** 4.1.7

**Results of `show plugins` command in console:**
Exiled Permissions
Exiled Events
Exiled Custom Roles
Exiled Custom Items

**Comment by joker-119** [comment]
The cancelling of his rage if all his targets die before his enrage animation is complete was to counter a bug present in 11.0 iirc.
I think the best course of action is to keep that slight change from base-game functionality but make sure the extra time is properly reset when this happens.

**Comment by Xypixian** [comment]
As a designer regarding this, I'd say that's not a good idea.
An important weakness of 096 is him exiting rage. If he is spotted even once, he should rage and enter cooldown. Death of targets should not matter.
Getting put into an undesirable situation when you have to go through a full rage cycle, complete with the vulnerabilities afterwards, even for a single target, is part of 096's gameplay.

**Comment by AgentBlackout** [comment]
> As a designer regarding this, I'd say that's not a good idea. An important weakness of 096 is him exiting rage. If he is spotted even once, he should rage and enter cooldown. Death of targets should not matter. Getting put into an undesirable situation when you have to go through a full rage cycle, complete with the vulnerabilities afterwards, even for a single target, is part of 096's gameplay.

Cope

**Comment by joker-119** [comment]
> As a designer regarding this, I'd say that's not a good idea. An important weakness of 096 is him exiting rage. If he is spotted even once, he should rage and enter cooldown. Death of targets should not matter. Getting put into an undesirable situation when you have to go through a full rage cycle, complete with the vulnerabilities afterwards, even for a single target, is part of 096's gameplay.

The main issue with this is, for example, when a plugin clears his target list in the StartingEnrage event. If, in this example, the plugin doesn't want Chaos Insurgency to be able to trigger his enrage, all that plugin needs to do is remove chaos players from his target list when he's trying to start the enrage process. This keeps him from enraging, but if we force him into his enrage even if the target list is empty, this will trigger his cooldown and effectively kills his gameplay when said plugin is on the server.
