### ISSUE TITLE
Unban request from Discord

### ISSUE THREAD

**Issue by badboi2004** [Exiled-Team/EXILED#960]
Good evening! 
I would like to do a ban appeal if it's possible.I know it's my fault since I wasn't making sure my discord account isn't getting hacked.That's why there were "free nitro links" which were spammed on my account by a bot.My discord name is:Peter4k#7263
Have a good day.
-Peter

**Comment by joker-119** [comment]
Ban removed. Please take the necessary steps to ensure your account remains secure, if it is hacked and this happens again the ban will be permanent.
