### ISSUE TITLE
[NRE] ragdoll.Delete() if ragdoll owner was disconnected from the server

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/EXILED#965]
**Exiled 4.1.7**

I have NRE in
`foreach (Exiled.API.Features.Ragdoll ragdoll in Map.Ragdolls.ToList()) ragdoll.Delete();`
If someone of ragdolls owner was disconnected from the server

**Comment by joker-119** [comment]
The bug report template exists for a reason, please include all of the information requested in it so we can see the actual exception.
