### ISSUE TITLE
How do I add a custom SCP?

### ISSUE THREAD

**Issue by markisine** [Exiled-Team/EXILED#967]
I wondered how I can create a custom SCP that can spawn when at least 2 Players are SCP. Its function is just like SCP-938. it should be able to lock doors disable lights and if it’s possible temporarily disable SCP-914. I know I’m going to post this in issues but I didn’t find the questions tab.

**Comment by joker-119** [comment]
Use the custom roles API, as demonstrated in this plugin: https://github.com/joker-119/CustomRoles/tree/master/CustomRoles
